version: '3.1'

services:
  simple_langchain_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: simple_langchain
      POSTGRES_PASSWORD: simple_langchain
      POSTGRES_DB: simple_langchain
    ports:
      - "5432:5432"